### ISSUE TITLE
Implement !rematch

### ISSUE THREAD

**Issue by kelostrada** [kelostrada/chitczat#10]
This should move people back to the queue so some missing person might be added for example and matched again

**Comment by agusmoles** [comment]
In this case I would also need more information about the decisions of the project like how are we going to manage db collections, etc. to figure out which would be the best approach. Maybe we can have a quick call about that

**Comment by kelostrada** [comment]
So this should actually be pretty straightforward - when you issue this command you will take all the people who are in the last record of `matches` collection. You remove that record and mark everyone who was there as `added` again. So they appear in queue again and new people can still be added if something needs to be fixed (someone wanted to join just after Anna issued `!match` command)

This will obviously conflict a bit with matches refactor so we should probably take care of the refactor first before tackling stuff like this ;) But this doesn't require any database changes or whatsoever
