### ISSUE TITLE
Randomize the collection of people before running the matching algorithm

### ISSUE THREAD

**Issue by kelostrada** [kelostrada/chitczat#9]
The matching algorithm is deterministic. That means that for instance people who signed up first will have much higher chance to get matched together but very low chance of getting matched with people who signed up last

**Comment by agusmoles** [comment]
Could you explain which algorithm are we using right now in the readme so we are able to look for more documentation about it since code is so imperative and difficult to understand?

**Comment by kelostrada** [comment]
Added some comments here: https://github.com/kelostrada/chitczat/blob/master/README.md#matching-algorithm

**Comment by agusmoles** [comment]
@kelostrada this issue should be closed, right?

**Comment by kelostrada** [comment]
done!
